### ISSUE TITLE
Поддерживается ли автоматическое прохождение MONETA.Assistant?

### ISSUE THREAD

**Issue by nedden** [RuntimeLLC/payanyway#18]
Привет! 

Я не нашел поддержки параметров paymentSystem.accountId, javascriptEnabled, followup

**Comment by ssnickolay** [comment]
@nedden привет! Что-то я не вижу этих параметров в документации
https://www.payanyway.ru/info/p/ru/public/merchants/PAWIntegrationOverview.pdf
можешь уточнить о них упоминается?

**Comment by nedden** [comment]
Читаю эту документацию - https://www.moneta.ru/doc/MONETA.Assistant.ru.pdf

**Comment by ssnickolay** [comment]
Вспомнил, спасибо..по-моему, в первых версиях gem'a они поддерживались, потому убрали за ненадобностью...
У Вас есть потребность в этих опциях?

**Comment by nedden** [comment]
Я хочу использовать автоматический режим. А почему убрали?

**Comment by llxff** [comment]
@nedden привет. Как временное решение можно попробовать переопределить константу `Payanyway::Factories::PaymentUrlFactory::PARAMS`, добавив туда маппинг нужных полей

```
Payanyway::Factories::PaymentUrlFactory::PARAMS = {
  # ... изначальные поля
  # и например:

  'paymentSystem.accountId' => :payment_system_account_id
}.to_settings
```

Полный маппинг описан тут: https://github.com/RuntimeLLC/payanyway/blob/master/lib/payanyway/factories/payment_url_factory.rb#L4

Не могу гарантировать, что сработает, но на быстром тесте вроде как верно добавляет поля

```
[19] pry(main)> Payanyway::Gateway.payment_url({ payment_system_account_id: 1}, false)
=> "https://demo.moneta.ru/assistant.htm?...&paymentSystem.accountId=1"
```

Вы можете попробовать сделать pull request самостоятельно, потому что пока не сможем добавить поддержку в ближайшее время (пока есть срочные задачи на основном проекте), надеюсь Вы нас поймете.

**Comment by ssnickolay** [comment]
https://github.com/RuntimeLLC/payanyway/releases/tag/v2.1.0
Описание использования можно посмотреть в обновлённом README.
