### ISSUE TITLE
Rails 4 - render plain - ActionView::MissingTemplate

### ISSUE THREAD

**Issue by kanfet** [RuntimeLLC/payanyway#23]
Этот коммит https://github.com/RuntimeLLC/payanyway/commit/35a46e05f6142f1260eedb77832af041160bd68d сломал работу гема в rails 4. В результате выбрасывается исключение ActionView::MissingTemplate

**Comment by llxff** [comment]
привет, можешь сделать пул реквест с проверкой, если rails >= 5.1, то render :text, иначе render :plain с тестом? А мы потом быстро апнем гем?

**Comment by kanfet** [comment]
https://github.com/RuntimeLLC/payanyway/pull/24

**Comment by llxff** [comment]
Исправлено в 2.2.2
